from tkinter import *
from tkinter import ttk
import sqlite3

#Define globals
helpWindow = None                    # put it in globals so can be destroyed by other functions

# é ö

def setupDB():
    cursor.execute("DROP TABLE IF EXISTS Author")
    cursor.execute("DROP TABLE IF EXISTS Penname")
    cursor.execute("DROP TABLE IF EXISTS Author_Book")
    cursor.execute("DROP TABLE IF EXISTS Book")
    cursor.execute("DROP TABLE IF EXISTS Also_Titled")
    cursor.execute("DROP TABLE IF EXISTS Includes")
    cursor.execute("DROP TABLE IF EXISTS Book_Note")
    cursor.execute("DROP TABLE IF EXISTS Series_Book")
    cursor.execute("DROP TABLE IF EXISTS Series")
    cursor.execute("DROP TABLE IF EXISTS Rating")
    
    cursor.execute("CREATE TABLE Author(Id INT, Given_Name TEXT, Family_Name TEXT)")
    cursor.execute("INSERT INTO Author VALUES(1, 'Isaac', 'Asimov')")
    cursor.execute("INSERT INTO Author VALUES(2, 'Robert', 'Heinlein')")
    cursor.execute("INSERT INTO Author VALUES(3, 'Terry', 'Pratchett')")
    cursor.execute("INSERT INTO Author VALUES(4, 'Bob', 'Shaw')")
    cursor.execute("INSERT INTO Author VALUES(5, 'Bill', 'Bryson')")
    cursor.execute("INSERT INTO Author VALUES(6, 'Sadie', 'Jones')")
    cursor.execute("INSERT INTO Author VALUES(7, 'Patricia', 'Highsmith')")
    cursor.execute("INSERT INTO Author VALUES(8, 'Lawrence', 'Block')")
    cursor.execute("INSERT INTO Author VALUES(9, 'Ursula', 'le Guin')")
    cursor.execute("INSERT INTO Author VALUES(10, 'Jonathan', 'Safran Foer')")
    cursor.execute("INSERT INTO Author VALUES(11, 'Susan', 'Hill')")
    cursor.execute("INSERT INTO Author VALUES(12, 'Charles', 'Dickens')")
    cursor.execute("INSERT INTO Author VALUES(13, 'Keith', 'Laumer')")
    cursor.execute("INSERT INTO Author VALUES(14, 'Roddy', 'Doyle')")
    cursor.execute("INSERT INTO Author VALUES(15, 'Jack', 'McDevitt')")
    cursor.execute("INSERT INTO Author VALUES(16, 'Steven', 'Pinker')")
    cursor.execute("INSERT INTO Author VALUES(17, 'Andy', 'Mulligan')")
    cursor.execute("INSERT INTO Author VALUES(18, 'C.J.', 'Sansom')")
    cursor.execute("INSERT INTO Author VALUES(19, 'John', 'Harding')")
    cursor.execute("INSERT INTO Author VALUES(20, 'China', 'Miéville')")
    cursor.execute("INSERT INTO Author VALUES(21, 'Carys', 'Bray')")
    cursor.execute("INSERT INTO Author VALUES(22, 'Robert J.', 'Sawyer')")
    cursor.execute("INSERT INTO Author VALUES(23, 'Robert', 'Bloch')")
    cursor.execute("INSERT INTO Author VALUES(24, 'Harlan', 'Coben')")
    cursor.execute("INSERT INTO Author VALUES(25, 'David', 'Ramirez')")
    cursor.execute("INSERT INTO Author VALUES(26, 'Anders', 'Roslund')")
    cursor.execute("INSERT INTO Author VALUES(27, 'Börge', 'Hellström')")
    cursor.execute("INSERT INTO Author VALUES(28, 'Ali', 'Smith')")
    cursor.execute("INSERT INTO Author VALUES(29, 'Beryl', 'Bainbridge')")
    cursor.execute("INSERT INTO Author VALUES(30, 'Charlotte', 'Roche')")
    cursor.execute("INSERT INTO Author VALUES(31, 'Joseph', 'Finder')")
    cursor.execute("INSERT INTO Author VALUES(32, 'Kate', 'Atkinson')")
    cursor.execute("INSERT INTO Author VALUES(33, 'Michael', 'Ashley')")
    cursor.execute("INSERT INTO Author VALUES(34, 'Peter', 'Haining')")
    cursor.execute("INSERT INTO Author VALUES(35, 'Richard', 'Dalby')")
    cursor.execute("INSERT INTO Author VALUES(36, 'Kelley', 'Armstrong')")
    cursor.execute("INSERT INTO Author VALUES(37, 'Ernest', 'Cline')")
    cursor.execute("INSERT INTO Author VALUES(38, 'Laline', 'Paull')")
    cursor.execute("INSERT INTO Author VALUES(39, 'Jessie', 'Burton')")
    cursor.execute("INSERT INTO Author VALUES(40, 'Phil', 'Klay')")
    cursor.execute("INSERT INTO Author VALUES(41, 'Alastair', 'Reynolds')")
    cursor.execute("INSERT INTO Author VALUES(42, 'Malcolm', 'Gladwell')")
    cursor.execute("INSERT INTO Author VALUES(43, 'Audrey', 'Niffenegger')")
    cursor.execute("INSERT INTO Author VALUES(44, 'Richard', 'Thaler')")
    cursor.execute("INSERT INTO Author VALUES(45, 'Gary', 'Gibson')")
    cursor.execute("INSERT INTO Author VALUES(46, 'Daniel', 'Kahneman')")
    cursor.execute("INSERT INTO Author VALUES(47, 'John G.', 'Hemry')")
    cursor.execute("INSERT INTO Author VALUES(48, 'Jack', 'Campbell')")
    cursor.execute("INSERT INTO Author VALUES(49, 'Gardner R.', 'Dozois')")
    cursor.execute("INSERT INTO Author VALUES(50, 'Greg', 'Egan')")
    cursor.execute("INSERT INTO Author VALUES(51, 'Marlon', 'James')")
    cursor.execute("INSERT INTO Author VALUES(52, 'Larry', 'Niven')")
    cursor.execute("INSERT INTO Author VALUES(53, 'Ian', 'McDonald')")
    cursor.execute("INSERT INTO Author VALUES(54, 'David', 'Wingrove')")
    cursor.execute("INSERT INTO Author VALUES(55, 'David', 'Vann')")
    cursor.execute("INSERT INTO Author VALUES(56, 'Ann', 'Leckie')")
    cursor.execute("INSERT INTO Author VALUES(57, 'Hanya', 'Yanagihara')")
    cursor.execute("INSERT INTO Author VALUES(58, 'Neal', 'Stephenson')")
    cursor.execute("INSERT INTO Author VALUES(59, 'Robert', 'Dinsdale')")
    cursor.execute("INSERT INTO Author VALUES(60, 'Stephen', 'Baxter')")
    cursor.execute("INSERT INTO Author VALUES(61, 'Ninni', 'Holmqvist')")
    cursor.execute("INSERT INTO Author VALUES(62, 'Cory', 'Doctorow')")
    cursor.execute("INSERT INTO Author VALUES(63, 'Joseph', 'O''Neill')")
    cursor.execute("INSERT INTO Author VALUES(64, 'Helen', 'Oyeyemi')")
    cursor.execute("INSERT INTO Author VALUES(65, 'Elliot', 'Perlman')")
    cursor.execute("INSERT INTO Author VALUES(66, 'Matt', 'Haig')")
    cursor.execute("INSERT INTO Author VALUES(67, 'John-Henri', 'Holmberg')")
    cursor.execute("INSERT INTO Author VALUES(68, 'Cynthia', 'Ozick')")
    cursor.execute("INSERT INTO Author VALUES(69, 'Philip K.', 'Dick')")
    cursor.execute("INSERT INTO Author VALUES(70, 'Hannu', 'Rajaniemi')")
    cursor.execute("INSERT INTO Author VALUES(71, 'Ruth L.', 'Ozeki')")
    cursor.execute("INSERT INTO Author VALUES(72, 'Michael', 'Cox')")
    cursor.execute("INSERT INTO Author VALUES(73, 'Ken', 'MacLeod')")
    cursor.execute("INSERT INTO Author VALUES(74, 'David Thomas', 'Moore')")
    cursor.execute("INSERT INTO Author VALUES(75, 'David', 'Brin')")
    cursor.execute("INSERT INTO Author VALUES(76, 'Cormac', 'McCarthy')")
    cursor.execute("INSERT INTO Author VALUES(77, 'Mike', 'Resnick')")
    cursor.execute("INSERT INTO Author VALUES(78, 'J.', 'Haldeman')")
    cursor.execute("INSERT INTO Author VALUES(79, 'M.H.', 'Greenberg')")
    cursor.execute("INSERT INTO Author VALUES(80, 'E.T.', 'Reynolds')")
    cursor.execute("INSERT INTO Author VALUES(81, 'Sir Arthur', 'Conan Doyle')")
    cursor.execute("INSERT INTO Author VALUES(82, 'Poul', 'Anderson')")
    cursor.execute("INSERT INTO Author VALUES(83, 'William', 'Sutcliffe')")
    cursor.execute("INSERT INTO Author VALUES(84, 'Robert', 'Harris')")
    cursor.execute("INSERT INTO Author VALUES(85, 'James S.A.', 'Corey')")
    cursor.execute("INSERT INTO Author VALUES(86, 'Daniel', 'Abraham')")
    cursor.execute("INSERT INTO Author VALUES(87, 'Ty', 'Franck')")
    cursor.execute("INSERT INTO Author VALUES(88, 'Sarah', 'Waters')")
    cursor.execute("INSERT INTO Author VALUES(89, 'Tim', 'Walker')")
    cursor.execute("INSERT INTO Author VALUES(90, 'Charlaine', 'Harris')")
    cursor.execute("INSERT INTO Author VALUES(91, 'Toni L.P.', 'Kelner')")
    cursor.execute("INSERT INTO Author VALUES(92, 'Michael', 'Chabon')")
    cursor.execute("INSERT INTO Author VALUES(93, 'Raymond', 'Chandler')")
    cursor.execute("INSERT INTO Author VALUES(94, 'Charles', 'Stross')")
    cursor.execute("INSERT INTO Author VALUES(95, 'Peter F.', 'Hamilton')")
    cursor.execute("INSERT INTO Author VALUES(96, 'Terry', 'Hayes')")
    cursor.execute("INSERT INTO Author VALUES(97, 'Paula', 'Hawkins')")
    cursor.execute("INSERT INTO Author VALUES(98, 'Kate', 'Mosse')")
    cursor.execute("INSERT INTO Author VALUES(99, 'Suzanne', 'Collins')")
    cursor.execute("INSERT INTO Author VALUES(100, 'Hanif', 'Kureishi')")
    cursor.execute("INSERT INTO Author VALUES(101, 'Terry', 'Goodkind')")
    cursor.execute("INSERT INTO Author VALUES(102, 'Elizabeth', 'Strout')")
    cursor.execute("INSERT INTO Author VALUES(103, 'Essie', 'Fox')")
    cursor.execute("INSERT INTO Author VALUES(104, 'Rachel', 'Ward')")
    cursor.execute("INSERT INTO Author VALUES(105, 'Karen Joy', 'Fowler')")
    cursor.execute("INSERT INTO Author VALUES(106, 'T.C.', 'Boyle')")
    cursor.execute("INSERT INTO Author VALUES(107, 'Jill', 'Dawson')")
    cursor.execute("INSERT INTO Author VALUES(108, 'Raymond', 'Briggs')")

    cursor.execute("CREATE TABLE Penname(Author INT, Penname INT)")
    cursor.execute("INSERT INTO Penname VALUES(47, 48)")
    cursor.execute("INSERT INTO Penname VALUES(86, 85)")
    cursor.execute("INSERT INTO Penname VALUES(87, 85)")

    cursor.execute("CREATE TABLE Author_Book(Book INT, Author INT, Comment TXT)")
    cursor.execute("INSERT INTO Author_Book VALUES(1, 1, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(2, 2, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(3, 2, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(4, 2, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(5, 6, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(6, 7, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(7, 8, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(8, 8, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(9, 3, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(10, 9, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(11, 10, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(12, 11, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(13, 12, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(14, 3, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(15, 3, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(16, 13, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(17, 14, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(18, 15, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(19, 16, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(20, 17, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(21, 18, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(22, 8, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(23, 19, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(24, 20, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(25, 3, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(26, 8, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(27, 21, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(28, 22, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(29, 22, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(30, 22, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(31, 22, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(32, 23, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(33, 24, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(34, 25, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(35, 22, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(36, 26, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(36, 27, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(37, 28, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(38, 28, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(39, 29, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(40, 30, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(41, 31, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(42, 32, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(43, 33, 'Editor')")
    cursor.execute("INSERT INTO Author_Book VALUES(44, 29, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(45, 34, 'Editor')")
    cursor.execute("INSERT INTO Author_Book VALUES(46, 35, 'Editor')")
    cursor.execute("INSERT INTO Author_Book VALUES(47, 36, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(48, 37, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(49, 38, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(50, 39, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(51, 3, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(52, 40, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(53, 41, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(54, 41, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(55, 41, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(56, 42, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(57, 43, 'Editor')")
    cursor.execute("INSERT INTO Author_Book VALUES(58, 44, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(59, 45, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(60, 45, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(61, 45, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(62, 45, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(63, 42, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(64, 46, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(65, 47, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(66, 47, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(67, 47, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(68, 47, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(69, 47, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(70, 47, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(71, 47, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(72, 47, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(73, 47, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(74, 47, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(75, 47, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(76, 49, 'Editor')")
    cursor.execute("INSERT INTO Author_Book VALUES(77, 50, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(78, 50, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(79, 50, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(80, 51, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(81, 52, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(82, 52, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(83, 52, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(84, 52, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(85, 52, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(86, 18, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(87, 53, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(88, 53, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(89, 54, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(90, 54, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(91, 54, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(92, 54, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(93, 54, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(94, 54, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(95, 54, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(96, 54, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(97, 8, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(98, 16, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(99, 15, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(100, 55, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(101, 56, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(102, 56, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(103, 56, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(104, 33, 'Editor')")
    cursor.execute("INSERT INTO Author_Book VALUES(105, 57, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(106, 58, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(107, 59, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(108, 60, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(108, 3, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(109, 60, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(109, 3, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(110, 60, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(110, 3, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(111, 60, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(111, 3, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(112, 60, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(112, 3, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(113, 61, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(114, 62, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(115, 63, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(116, 64, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(117, 65, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(118, 66, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(119, 67, 'Editor')")
    cursor.execute("INSERT INTO Author_Book VALUES(120, 68, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(121, 20, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(122, 69, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(123, 70, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(124, 70, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(125, 70, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(126, 15, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(127, 49, 'Editor')")
    cursor.execute("INSERT INTO Author_Book VALUES(128, 71, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(129, 72, 'Editor')")
    cursor.execute("INSERT INTO Author_Book VALUES(130, 15, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(131, 73, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(132, 74, 'Editor')")
    cursor.execute("INSERT INTO Author_Book VALUES(133, 75, 'Editor')")
    cursor.execute("INSERT INTO Author_Book VALUES(134, 8, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(135, 18, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(136, 76, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(137, 18, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(138, 77, 'Editor')")
    cursor.execute("INSERT INTO Author_Book VALUES(139, 78, 'Editor')")
    cursor.execute("INSERT INTO Author_Book VALUES(139, 79, 'Editor')")
    cursor.execute("INSERT INTO Author_Book VALUES(140, 80, 'Editor')")
    cursor.execute("INSERT INTO Author_Book VALUES(141, 80, 'Editor')")
    cursor.execute("INSERT INTO Author_Book VALUES(142, 81, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(143, 82, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(144, 83, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(145, 1, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(146, 84, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(147, 36, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(148, 84, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(149, 86, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(149, 87, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(150, 88, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(151, 89, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(152, 90, 'Editor')")
    cursor.execute("INSERT INTO Author_Book VALUES(152, 91, 'Editor')")
    cursor.execute("INSERT INTO Author_Book VALUES(153, 92, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(154, 93, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(155, 93, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(156, 93, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(157, 94, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(158, 94, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(159, 94, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(160, 94, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(161, 94, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(162, 94, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(163, 94, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(164, 94, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(165, 94, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(166, 8, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(167, 15, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(168, 95, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(169, 96, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(170, 97, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(171, 98, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(172, 99, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(173, 9, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(174, 9, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(175, 9, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(176, 9, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(177, 9, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(178, 100, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(179, 101, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(180, 8, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(181, 3, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(182, 102, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(183, 41, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(184, 103, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(185, 53, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(186, 81, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(187, 94, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(188, 15, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(189, 81, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(190, 76, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(191, 81, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(192, 18, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(193, 104, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(194, 105, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(195, 106, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(196, 107, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(197, 84, '')")
    cursor.execute("INSERT INTO Author_Book VALUES(198, 108, '')")

    cursor.execute("CREATE TABLE Book(Id INT, Title TEXT, Comment TEXT, Rating TEXT)")
    cursor.execute("INSERT INTO Book VALUES(1, 'I, Robot', 'Good', 'A')")
    cursor.execute("INSERT INTO Book VALUES(2, 'Double Star', 'Brilliant', 'R')")
    cursor.execute("INSERT INTO Book VALUES(3, 'Stranger in a Strange Land', 'Brilliant', 'R')")
    cursor.execute("INSERT INTO Book VALUES(4, 'Starship Trooper', 'Brilliant', 'R')")
    cursor.execute("INSERT INTO Book VALUES(5, 'Fallout', 'Very good. Ending just right', 'A')")
    cursor.execute("INSERT INTO Book VALUES(6, 'Those Who Walk Away', 'Tedious, with unappealing characters. Managed approx half', 'N')")
    cursor.execute("INSERT INTO Book VALUES(7, 'Hit and Run', 'Great character - this is a novel not shorts', 'A')")
    cursor.execute("INSERT INTO Book VALUES(8, 'Hit Parade', 'Excellent. Shorts about Keller', 'R')")
    cursor.execute("INSERT INTO Book VALUES(9, 'Dodger', 'Didactic, some interesting info about Victorian London, but characters are too wooden. Managed approx half', 'T')")
    cursor.execute("INSERT INTO Book VALUES(10, 'The Dispossessed', 'Very good - set in an anarcho-communist society, ruled by social pressure, in a scarcity economy', 'M')")
    cursor.execute("INSERT INTO Book VALUES(11, 'Extremely Loud and Incredibly Close', 'Asperger boy on a quest for his father', 'M')")
    cursor.execute("INSERT INTO Book VALUES(12, 'The Beacon', 'Family drama', 'M')")
    cursor.execute("INSERT INTO Book VALUES(13, 'A Tale of Two Cities', 'Prolix, melodramatic - Dickens', 'M')")
    cursor.execute("INSERT INTO Book VALUES(14, 'Monstrous Regiment', 'Lead characters all new. A bit too much message so rather lacking in his characteristic humour', 'M')")
    cursor.execute("INSERT INTO Book VALUES(15, 'Equal Rites', 'Has Granny Weatherwax, but not the other witches. A female wizard challenges UU traditions - features Granny Weatherwax', 'R')")
    cursor.execute("INSERT INTO Book VALUES(16, 'Retief''s Ransom', 'Imaginative and humorous - with flying kidneys', 'R')")
    cursor.execute("INSERT INTO Book VALUES(17, 'A Greyhound of a Girl', 'Slightly young adult, but good', 'M')")
    cursor.execute("INSERT INTO Book VALUES(18, 'Starhawk', 'Characters shallow despite author''s efforts, and rather non-PC. Doesn''t grip', 'M')")
    cursor.execute("INSERT INTO Book VALUES(19, 'The Better Angels of Our Nature', 'Violence has been reducing over the centuries', 'A')")
    cursor.execute("INSERT INTO Book VALUES(20, 'The Boy with Two Heads', 'Slightly magical realism - uses two heaads as a physical metaphor for adolescence', 'T')")
    cursor.execute("INSERT INTO Book VALUES(21, 'Dark Fire', 'Quite fun, involving suspected Greek Fire', 'M')")
    cursor.execute("INSERT INTO Book VALUES(22, 'Hit Man', 'Excellent. Shorts about Keller', 'R')")
    cursor.execute("INSERT INTO Book VALUES(23, 'Florence and Giles', 'Excellent. Quite spooky', 'M')")
    cursor.execute("INSERT INTO Book VALUES(24, 'This Census-Taker', 'His usual unusual', 'M')")
    cursor.execute("INSERT INTO Book VALUES(25, 'Reaper Man', 'Death is fired by the Auditors', 'M')")
    cursor.execute("INSERT INTO Book VALUES(26, 'The Girl with the Deep Blue Eyes', 'Murder mystery', 'M')")
    cursor.execute("INSERT INTO Book VALUES(27, 'A Song for Issy Bradley', 'A mother cannot get over the death of her young daughter, and the family can''t help her', 'M')")
    cursor.execute("INSERT INTO Book VALUES(28, 'Wonder', 'Government hackers attempt to destroy Webmind', 'M')")
    cursor.execute("INSERT INTO Book VALUES(29, 'Watch', 'The government is getting worried about Webmind', 'M')")
    cursor.execute("INSERT INTO Book VALUES(30, 'Wake', 'Webmind awakes', 'M')")
    cursor.execute("INSERT INTO Book VALUES(31, 'Triggers', 'Memory sharing triggered by EMP', 'M')")
    cursor.execute("INSERT INTO Book VALUES(32, 'Psycho', 'The classic', 'T')")
    cursor.execute("INSERT INTO Book VALUES(33, 'Fool Me Once', 'Woman''s husband murdered - or is he really dead?', 'M')")
    cursor.execute("INSERT INTO Book VALUES(34, 'The Forever Watch', 'Generation ship - twist is that the humans have psychic powers. Thriller', 'M')")
    cursor.execute("INSERT INTO Book VALUES(35, 'Quantum Night', 'Three mental types of humans - but type can be flipped. Bit too elitist for my comfort, and the science was even weaker than usual for him', 'T')")
    cursor.execute("INSERT INTO Book VALUES(36, 'The Beast', 'Child rapist/killer hunted by police and fathet', 'T')")
    cursor.execute("INSERT INTO Book VALUES(37, 'How to be Both', 'Past connects to future - Renaissance girl painter and modern girl who has lost her mum', 'T')")
    cursor.execute("INSERT INTO Book VALUES(38, 'Public Library and Other Stories', 'Short stories - good', 'M')")
    cursor.execute("INSERT INTO Book VALUES(39, 'The Birthday Boys', 'Captain Scott''s polar expedition, told from various participant''s perspectives and finishes just perfectly', 'M')")
    cursor.execute("INSERT INTO Book VALUES(40, 'Wrecked', 'Semi-autobiographical - in therapy to deal with the death of her family, using sex to numb herself', 'A')")
    cursor.execute("INSERT INTO Book VALUES(41, 'The Fixer', 'Man finds millions hidden by his dead father - a fixer', 'M')")
    cursor.execute("INSERT INTO Book VALUES(42, 'Life After Life', 'Every time she dies she comes back with her life tweaked to avoid that death', 'M')")
    cursor.execute("INSERT INTO Book VALUES(43, 'The Mammoth Book of Apocalyptic SF', 'Good shorts', 'A')")
    cursor.execute("INSERT INTO Book VALUES(44, 'An Awfully Big Adventure', 'Life in the theatre post-war', 'A')")
    cursor.execute("INSERT INTO Book VALUES(45, 'The Mammoth Book of 20th Century Ghost Stories', 'Good shorts', 'M')")
    cursor.execute("INSERT INTO Book VALUES(46, 'The Mammoth Book of Victorian and Edwardian Ghost Stories', 'Good shorts', 'M')")
    cursor.execute("INSERT INTO Book VALUES(47, 'Bitten', 'Fun to read to Sheelagh - girl werewolf keeping away from her pack, while trying to live a normalish life - but young adult and a bit light', 'Y')")
    cursor.execute("INSERT INTO Book VALUES(48, 'Ready Player One', 'Imagine if a video game player could be a hero. Fun, but probably a one-off as ideas more than characters', 'T')")
    cursor.execute("INSERT INTO Book VALUES(49, 'The Bees', 'Slightly magical realism - women-bees in a stratified hive, with police and our rebel', 'T')")
    cursor.execute("INSERT INTO Book VALUES(50, 'The Miniaturist', 'Slightly magical realism - a Dutch doll''s house mirrors the events in the real house', 'T')")
    cursor.execute("INSERT INTO Book VALUES(51, 'A Blink of the Screen', 'Shorts - rather a mixed bag', 'T')")
    cursor.execute("INSERT INTO Book VALUES(52, 'Redeployment', 'Shorts about the Iraq war as a US serviceman - excellent', 'R')")
    cursor.execute("INSERT INTO Book VALUES(53, 'Blue Remembered Earth', 'Good read', 'A')")
    cursor.execute("INSERT INTO Book VALUES(54, 'On the Steel Breeze', 'Good read', 'A')")
    cursor.execute("INSERT INTO Book VALUES(55, 'Poseidon''s Wake', 'Good read', 'A')")
    cursor.execute("INSERT INTO Book VALUES(56, 'The Tipping Point', 'Interesting - how to make things happen', 'M')")
    cursor.execute("INSERT INTO Book VALUES(57, 'Ghostly', 'Shorts, ghost stories old and new', 'M')")
    cursor.execute("INSERT INTO Book VALUES(58, 'Nudge', 'Looks at how to nudge people to do things, and common decision errors', 'M')")
    cursor.execute("INSERT INTO Book VALUES(59, 'Marauder', 'Megan is embodied by mind-meld in Gabriella and can fly a ship', 'A')")
    cursor.execute("INSERT INTO Book VALUES(60, 'Stealing Light', 'Megan steals FTL', 'A')")
    cursor.execute("INSERT INTO Book VALUES(61, 'Nova War', 'The FTL drive can create novas', 'A')")
    cursor.execute("INSERT INTO Book VALUES(62, 'Empire of Light', 'Megan has to decode the asteroid code to save the universe', 'A')")
    cursor.execute("INSERT INTO Book VALUES(63, 'Outliers', 'Success comes from a confluence of factors, not innate genius', 'M')")
    cursor.execute("INSERT INTO Book VALUES(64, 'Thinking Fast and Slow', 'Looks common decision errors due to fast thinking', 'M')")
    cursor.execute("INSERT INTO Book VALUES(65, 'Dauntless', 'Black Jack found', 'A')")
    cursor.execute("INSERT INTO Book VALUES(66, 'Fearless', '', 'A')")
    cursor.execute("INSERT INTO Book VALUES(67, 'Courageous', '', 'A')")
    cursor.execute("INSERT INTO Book VALUES(68, 'Valient', '', 'A')")
    cursor.execute("INSERT INTO Book VALUES(69, 'Relentless', '', 'A')")
    cursor.execute("INSERT INTO Book VALUES(70, 'Victorious', '', 'A')")
    cursor.execute("INSERT INTO Book VALUES(71, 'Dreadnought', '', 'A')")
    cursor.execute("INSERT INTO Book VALUES(72, 'Invincible', '', 'A')")
    cursor.execute("INSERT INTO Book VALUES(73, 'Guardian', '', 'A')")
    cursor.execute("INSERT INTO Book VALUES(74, 'Steadfast', '', 'A')")
    cursor.execute("INSERT INTO Book VALUES(75, 'Leviathan', '', 'A')")
    cursor.execute("INSERT INTO Book VALUES(76, 'The Mammoth Book of Best New Science Fiction 28', 'Good shorts', 'A')")
    cursor.execute("INSERT INTO Book VALUES(77, 'The Clockwork Rocket', 'Brilliant universe - with website giving more theory', 'R')")
    cursor.execute("INSERT INTO Book VALUES(78, 'The Eternal Flame', 'Brilliant universe - with website giving more theory', 'R')")
    cursor.execute("INSERT INTO Book VALUES(79, 'The Arrows of Time', 'Brilliant universe - with website giving more theory', 'R')")
    cursor.execute("INSERT INTO Book VALUES(80, 'A Brief History of Seven Killings', 'Couldn''t get into it at all - gave up on it eventually', 'N')")
    cursor.execute("INSERT INTO Book VALUES(81, 'Ringworld', 'The original', 'A')")
    cursor.execute("INSERT INTO Book VALUES(82, 'The Ringworld Engineers', 'To correct engineering errors in the first book', 'A')")
    cursor.execute("INSERT INTO Book VALUES(83, 'The Ringworld Throne', 'Bram the vampire tries to take over', 'A')")
    cursor.execute("INSERT INTO Book VALUES(84, 'Ringworld''s Children', 'Everyone wants the Ringworld - so it heads off', 'A')")
    cursor.execute("INSERT INTO Book VALUES(85, 'Protector', 'How Pak became human', 'A')")
    cursor.execute("INSERT INTO Book VALUES(86, 'Sovereign', 'Shardlake discovers his king Henry VIII is a cuckoo in the royal nest', 'M')")
    cursor.execute("INSERT INTO Book VALUES(87, 'Luna: New Moon', 'The top moon business families duke it out', 'A')")
    cursor.execute("INSERT INTO Book VALUES(88, 'Brasyl', 'Set in three times, past, modern, future, all in Brazil', 'A')")
    cursor.execute("INSERT INTO Book VALUES(89, 'The Middle Kingdom', 'Intro to Chung Kuo', 'M')")
    cursor.execute("INSERT INTO Book VALUES(90, 'The Broken Wheel', 'Chung Kuo', 'M')")
    cursor.execute("INSERT INTO Book VALUES(91, 'The White Mountain', 'Chung Kuo', 'M')")
    cursor.execute("INSERT INTO Book VALUES(92, 'The Stone Within', 'Chung Kuo', 'M')")
    cursor.execute("INSERT INTO Book VALUES(93, 'Beneath the Tree of Heaven', 'Chung Kuo', 'M')")
    cursor.execute("INSERT INTO Book VALUES(94, 'White Moon, Red Dragon', 'Chung Kuo', 'M')")
    cursor.execute("INSERT INTO Book VALUES(95, 'Days of Bitter Strength', 'Chung Kuo', 'M')")
    cursor.execute("INSERT INTO Book VALUES(96, 'The Marriage of the Living Dark', 'Final novel of series, but publishers had forced an early end - originally there was going to be another', 'M')")
    cursor.execute("INSERT INTO Book VALUES(97, 'The Sins of the Fathers', 'Scudder''s first outing - boy kills girl, or did he?', 'R')")
    cursor.execute("INSERT INTO Book VALUES(98, 'How the Mind Works', 'Not explicitly the one which considers how competing circuits cause volition, but supports the same idea of brain modules (not necessarily distinct)', 'R')")
    cursor.execute("INSERT INTO Book VALUES(99, 'The Engines of God', 'First of Academy series - but there is a later-written prequel (which isn''t as readable as this)', 'A')")
    cursor.execute("INSERT INTO Book VALUES(100, 'Aquarium', 'Girl meets her estranged dad at an aquarium', 'M')")
    cursor.execute("INSERT INTO Book VALUES(101, 'Ancillary Justice', 'Breq is the only remnant of the ship she was ancillary to', 'A')")
    cursor.execute("INSERT INTO Book VALUES(102, 'Ancillary Sword', 'Breq is now a captain of a ship', 'A')")
    cursor.execute("INSERT INTO Book VALUES(103, 'Ancillary Mercy', 'Breq meets the empire''s mad ruler - and doppelgangers', 'A')")
    cursor.execute("INSERT INTO Book VALUES(104, 'The Mammoth Book of Mindblowing SF', 'Another mammoth', 'A')")
    cursor.execute("INSERT INTO Book VALUES(105, 'A Little Life', 'Four college friends, one disabled and talented, grow up', 'M')")
    cursor.execute("INSERT INTO Book VALUES(106, 'The Diamond Age', 'Neo-Victorians rule Shanghai in a stratified society, but a shake-up is coming', 'M')")
    cursor.execute("INSERT INTO Book VALUES(107, 'Little Exiles', 'English orphans sent to Australia under the auspices of a church', 'M')")
    cursor.execute("INSERT INTO Book VALUES(108, 'The Long Earth', 'Stepping first starts', 'M')")
    cursor.execute("INSERT INTO Book VALUES(109, 'The Long War', 'The US tries to extend its hegemony stepwise', 'M')")
    cursor.execute("INSERT INTO Book VALUES(110, 'The Long Mars', 'Mars stepwise', 'M')")
    cursor.execute("INSERT INTO Book VALUES(111, 'The Long Utopia', '''Insects'' from another galaxy invade an Earth', 'M')")
    cursor.execute("INSERT INTO Book VALUES(112, 'The Long Cosmos', 'We join the galactic community', 'M')")
    cursor.execute("INSERT INTO Book VALUES(113, 'The Unit', 'At 50 you may be needed for medical experiments', 'T')")
    cursor.execute("INSERT INTO Book VALUES(114, 'Eastern Standard Tribe', 'Not as gripping as usual, some people affliate to ''tribes''s based on time zone, splitting loyalties', 'A')")
    cursor.execute("INSERT INTO Book VALUES(115, 'The Dog', 'An American working in Dubai discovers different rules apply', 'T')")
    cursor.execute("INSERT INTO Book VALUES(116, 'Mr Fox', 'A writer is confronted by his creation', 'T')")
    cursor.execute("INSERT INTO Book VALUES(117, 'Three Dollars', 'A family man surviving the economic collapse of the 90s', 'T')")
    cursor.execute("INSERT INTO Book VALUES(118, 'The Humans', 'An alien has to masquarade as a human while deciding whom to kill to protect dangerous secrets, but becomes humanized', 'T')")
    cursor.execute("INSERT INTO Book VALUES(119, 'A Darker Shade', 'Swedish stories of murder, mystery & suspense', 'T')")
    cursor.execute("INSERT INTO Book VALUES(120, 'Foreign Bodies', 'Aunt Bea flies to Paris to fetch back her nephew for her brother', 'T')")
    cursor.execute("INSERT INTO Book VALUES(121, 'Embassytown', 'A human town on an alien world, a space traveller (immer) trying to communicate with the natives', 'A')")
    cursor.execute("INSERT INTO Book VALUES(122, 'Paycheck', 'A time traveller gives himself an envelope of trinkets which enable his past self to achieve success by helping at crucial moments', 'A')")
    cursor.execute("INSERT INTO Book VALUES(123, 'The Quantum Thief', 'Starts in the Dilemma Prison and the ideas keep getting better', 'R')")
    cursor.execute("INSERT INTO Book VALUES(124, 'The Fractal Prince', 'The city is being slowly eaten by datavores', 'R')")
    cursor.execute("INSERT INTO Book VALUES(125, 'The Causal Angel', 'Jean saves the solar system from itself', 'R')")
    cursor.execute("INSERT INTO Book VALUES(126, 'Polaris', 'Alex investigates what happened to the crew of the Polaris', 'A')")
    cursor.execute("INSERT INTO Book VALUES(127, 'The Mammoth Book of Best New Science Fiction 21', 'Good shorts', 'A')")
    cursor.execute("INSERT INTO Book VALUES(128, 'A Tale for the Time Being', 'Lunchbox found on the shore containing a girl''s diary obsesses Ruth', 'M')")
    cursor.execute("INSERT INTO Book VALUES(129, '12 Victorian Ghost Stories', 'Ghosties', 'T')")
    cursor.execute("INSERT INTO Book VALUES(130, 'A Talent for War', 'Did Sim really defeat the Ashiyyur?', 'A')")
    cursor.execute("INSERT INTO Book VALUES(131, 'Newton''s Wake', 'The ferocious Carlyles travel the universe via wormholes, fighting other human groups, but then stumble upon some very hostile alien tech', 'M')")
    cursor.execute("INSERT INTO Book VALUES(132, 'Two Hundred and Twenty-One Baker Streets', 'Shorts based in the Holmesian world - a couple excellent but mostly so-so', 'T')")
    cursor.execute("INSERT INTO Book VALUES(133, 'Existence', 'Orbital rubbish collector picks up a crystal ball inhabited by aliens - what do they want? Ending a bit too positive/sudden', 'M')")
    cursor.execute("INSERT INTO Book VALUES(134, 'Sinner Man', 'Man kills his wife by accident - decides to change his whole life becoming a gangster', 'A')")
    cursor.execute("INSERT INTO Book VALUES(135, 'Dissolution', 'Set during the Dissolution, but really a murder mystery', 'M')")
    cursor.execute("INSERT INTO Book VALUES(136, 'No country for old men', 'A case of money being hunted by drug runners and a killer using a cow-stunner', 'A')")
    cursor.execute("INSERT INTO Book VALUES(137, 'Revelation', 'Shardlake protects Catherine Parr from a serial killer', 'M')")
    cursor.execute("INSERT INTO Book VALUES(138, 'Alien Crimes', '', 'O')")
    cursor.execute("INSERT INTO Book VALUES(139, 'Future Weapons of War', '', 'O')")
    cursor.execute("INSERT INTO Book VALUES(140, 'Visual Journeys', '', 'O')")
    cursor.execute("INSERT INTO Book VALUES(141, 'Ruins Extraterrestrial', '', 'O')")
    cursor.execute("INSERT INTO Book VALUES(142, 'A Study in Scarlet', 'Holmes meets Watson', 'M')")
    cursor.execute("INSERT INTO Book VALUES(143, 'World Without Stars', 'Two intelligent species, one selectively breeding the other. Humans free the latter.', 'A')")
    cursor.execute("INSERT INTO Book VALUES(144, 'The Wall', 'A teen Jewish settler learns what life is for Palestinians behind the wall dividing his city from theirs', 'A')")
    cursor.execute("INSERT INTO Book VALUES(145, 'The Caves of Steel', 'Elijah Bailey investigating a murder starts to suspect his robot partner', 'A')")
    cursor.execute("INSERT INTO Book VALUES(146, 'Archangel', 'Comrade Stalin dies and the Politburo vie for power', 'M')")
    cursor.execute("INSERT INTO Book VALUES(147, 'Waking the Witch', 'YA PI witch investigates some murders with help from hunky men', 'Y')")
    cursor.execute("INSERT INTO Book VALUES(148, 'The Fear Index', 'A quant has an algorithm using the Fear Index, but then someone starts to stalk him', 'M')")
    cursor.execute("INSERT INTO Book VALUES(149, 'Leviathan Wakes', 'Alien virus turns space station into alien spaceship powered by a human mind - eventually', 'M')")
    cursor.execute("INSERT INTO Book VALUES(150, 'The Little Stranger', 'Ghost spreads death and madness in a family but is never revealed', 'M')")
    cursor.execute("INSERT INTO Book VALUES(151, 'Completion', 'A family and their house - the marriage, children, divorce and death, then house sale', 'M')")
    cursor.execute("INSERT INTO Book VALUES(152, 'An Apple for the Creature', 'Urban fantasy and supernatural shorts', 'M')")
    cursor.execute("INSERT INTO Book VALUES(153, 'The Yiddish Policemen''s Union', 'The Jewish homeland is the coast of Alaska, a detective (usual kind) tries to find a murderer. The writer refers to Chandler as inspiration but fails - too literary', 'T')")
    cursor.execute("INSERT INTO Book VALUES(154, 'The Big Sleep', 'General Sternwood, near death, is concerned about his wild daughter - he doesn''t know half of it', 'R')")
    cursor.execute("INSERT INTO Book VALUES(155, 'The Little Sister', 'A missing person case turns nasty', 'R')")
    cursor.execute("INSERT INTO Book VALUES(156, 'Farewell, My Lovely', 'Marlowe picks up the pieces left by Moose Malloy - big and determined to find Velma', 'R')")
    cursor.execute("INSERT INTO Book VALUES(157, 'The Family Trade', 'Miriam discovers her estranged family are princes in a parallel world', 'A')")
    cursor.execute("INSERT INTO Book VALUES(158, 'The Hidden Family', 'The family discover a third world they can walk too, complicating things somewhat', 'A')")
    cursor.execute("INSERT INTO Book VALUES(159, 'The Clan Corporate', 'Can Miriam save herself from being forced to marry the simple-minded son of the most powerful family?', 'A')")
    cursor.execute("INSERT INTO Book VALUES(160, 'The Merchants'' War', 'Now they have nuclear bombs', 'A')")
    cursor.execute("INSERT INTO Book VALUES(161, 'The Traders'' War', 'The Clan Corporate + The Merchants'' War in one binding', 'A')")
    cursor.execute("INSERT INTO Book VALUES(162, 'The Revolution Business', 'The FBI learns how to world-walk', 'A')")
    cursor.execute("INSERT INTO Book VALUES(163, 'The Bloodline Feud', 'Merchant Princes #1&2', 'A')")
    cursor.execute("INSERT INTO Book VALUES(164, 'The Revolution Trade', 'Merchant Princes #5&6', 'A')")
    cursor.execute("INSERT INTO Book VALUES(165, 'A Merchant Princes Omnibus', 'First six of the Merchant Princes books', 'A')")
    cursor.execute("INSERT INTO Book VALUES(166, 'Time to murder and create', 'A blackmailer is murdered - which of his victims did it?', 'A')")
    cursor.execute("INSERT INTO Book VALUES(167, 'Deepsix', 'Same basic plot as previous in series - race to escape the planet before being destroyed', 'T')")
    cursor.execute("INSERT INTO Book VALUES(168, 'The Dreaming Void', 'Large cast of characters, rather hard to follow. Sect attempting to enter the Void, everyone else trying to stop or control them by finding their promised leader. Same history sequence as previous novels, but set much later', 'A')")
    cursor.execute("INSERT INTO Book VALUES(169, 'I am Pilgrim', 'Spy thriller - good fun but all a bit too coincidental, interesting idea but details ignored for the plot', 'T')")
    cursor.execute("INSERT INTO Book VALUES(170, 'The Girl on the Train', 'Good story, good twist', 'M')")
    cursor.execute("INSERT INTO Book VALUES(171, 'Labyrinth', 'Another modern quest for the Grail - Sheelagh liked it but seemed too silly to me', 'N')")
    cursor.execute("INSERT INTO Book VALUES(172, 'The Hunger Games', 'Teen-fiction but good fun', 'M')")
    cursor.execute("INSERT INTO Book VALUES(173, 'A Wizard of Earthsea', 'Sparrowhawk/Ged grows up and becomes a wizard', 'M')")
    cursor.execute("INSERT INTO Book VALUES(174, 'The Tombs of Atuan', 'Sparrowhawk retrieves the other half of a bracelet', 'M')")
    cursor.execute("INSERT INTO Book VALUES(175, 'The Farthest Shore', 'Sparrowhawk saves Earthsea from being drawn into the domain of death', 'M')")
    cursor.execute("INSERT INTO Book VALUES(176, 'Tehanu', 'The girl rescued by Sparrowhawk rescues a dragongirl - who then rescues them both', 'M')")
    cursor.execute("INSERT INTO Book VALUES(177, 'The Earthsea Quartet', 'Sparrowhawk from birth to death', 'M')")
    cursor.execute("INSERT INTO Book VALUES(178, 'Intimacy', 'The thoughts of a middle-aged father - a serial adulterer - as he leaves his family', 'M')")
    cursor.execute("INSERT INTO Book VALUES(179, 'Nest', 'If you could tell a killer by looking into their eyes... good idea ruined by tedious exposition', 'N')")
    cursor.execute("INSERT INTO Book VALUES(180, 'In the Midst of Death', 'A police office asks Scudder to help clear his name - but is he really innocent?', 'A')")
    cursor.execute("INSERT INTO Book VALUES(181, 'A Hat Full of Sky', 'Tiffany Aching gains her witch''s spurs fighting a hiver', 'M')")
    cursor.execute("INSERT INTO Book VALUES(182, 'Olive Kitteridge', 'Vignettes from a life lived in small town USA', 'M')")
    cursor.execute("INSERT INTO Book VALUES(183, 'Slow Bullets', 'Good set up, but peters out rather at the end. Skip ship arrives x000 years late to find humans reduced to middle ages on their planets, due to aliens temporarily tweaking universal constants locally. Rather arbitrary and not developed, just a McGuffin.', 'M')")
    cursor.execute("INSERT INTO Book VALUES(184, 'The Last Days of Leda Grey', 'Reclusive silent film star tracked down by reporter. Ghost-y story, but not explicitly till the end, so not made much of. Characters fine, but dialogue a bit forced at times', 'T')")
    cursor.execute("INSERT INTO Book VALUES(185, 'Luna: Wolf Moon', 'Lucas Corta has his revenge and takes over the Moon', 'A')")
    cursor.execute("INSERT INTO Book VALUES(186, 'The Sign of the Four', 'The second Holmes novel - Sholto, blowpipes and a river chase', 'A')")
    cursor.execute("INSERT INTO Book VALUES(187, 'The Trade of Queens', '', 'O')")
    cursor.execute("INSERT INTO Book VALUES(188, 'Chindi', 'Hutch investigates an alien spacecraft and its galaxy-wide satellite network. Usual last-minute rescues but well done', 'A')")
    cursor.execute("INSERT INTO Book VALUES(189, 'The Hound of the Baskervilles', 'The Great Grimpen Mire actually claims more victims than the Hellish Hound', 'R')")
    cursor.execute("INSERT INTO Book VALUES(190, 'Child of God', 'A man descends to the depths of sane madness, making love to his corpse brides', 'A')")
    cursor.execute("INSERT INTO Book VALUES(191, 'The Valley of Fear', 'Second half the book is the preamble, but a nice plot', 'R')")
    cursor.execute("INSERT INTO Book VALUES(192, 'Heartstone', 'Shardlake nearly goes down with the Mary Rose', 'M')")
    cursor.execute("INSERT INTO Book VALUES(193, 'Numbers', 'Gem can see people\'s death date. Not used in the plot, but a fun \'odd couple escape and fall in love\' teen novel', 'M')")
    cursor.execute("INSERT INTO Book VALUES(194, 'Sarah Canary', 'Sarah is essentially a McGuffin, the other principle characters pursuing or protecting her, though she seems insensible to them all', 'M')")
    cursor.execute("INSERT INTO Book VALUES(195, 'The Terranauts', '8 people locked into the Eden Project for two years', 'M')")
    cursor.execute("INSERT INTO Book VALUES(196, 'The Tell-tale Heart', 'A philanderer has a heart transplant - does he have a change of heart?', 'M')")
    cursor.execute("INSERT INTO Book VALUES(197, 'Enigma', 'A fictional account of a man working at Bletchley Park, with a spy thrown in', 'A')")
    cursor.execute("INSERT INTO Book VALUES(198, 'When the Wind Blows', 'A retired couple prepare for WWIII using some doors and white paint and government leaflets', 'M')")
#    cursor.execute("INSERT INTO Book VALUES(1, '', '', '')")

    cursor.execute("CREATE TABLE Also_Titled(Book_Id INT, Title TXT)")
    cursor.execute("INSERT INTO Also_Titled VALUES(185, 'The Sign of Four')")

    cursor.execute("CREATE TABLE Includes(Book_Id INT, Inclusion INT)")
    cursor.execute("INSERT INTO Includes VALUES(161, 159)")
    cursor.execute("INSERT INTO Includes VALUES(161, 160)")
    cursor.execute("INSERT INTO Includes VALUES(163, 157)")
    cursor.execute("INSERT INTO Includes VALUES(163, 158)")
    cursor.execute("INSERT INTO Includes VALUES(164, 162)")
    cursor.execute("INSERT INTO Includes VALUES(164, 187)")
    cursor.execute("INSERT INTO Includes VALUES(165, 157)")
    cursor.execute("INSERT INTO Includes VALUES(165, 158)")
    cursor.execute("INSERT INTO Includes VALUES(165, 159)")
    cursor.execute("INSERT INTO Includes VALUES(165, 160)")
    cursor.execute("INSERT INTO Includes VALUES(165, 162)")
    cursor.execute("INSERT INTO Includes VALUES(165, 187)")

    cursor.execute("CREATE TABLE Book_Note(Book_Id INT, Note TXT)")
    cursor.execute("INSERT INTO Book_Note VALUES(7, 'Novel')")
    cursor.execute("INSERT INTO Book_Note VALUES(8, 'Short stories')")
    cursor.execute("INSERT INTO Book_Note VALUES(22, 'Short stories')")
    cursor.execute("INSERT INTO Book_Note VALUES(18, 'Published 7th but a prequel')")
    cursor.execute("INSERT INTO Book_Note VALUES(78, '2015 collection')")
    cursor.execute("INSERT INTO Book_Note VALUES(127, '2008 collection')")
    cursor.execute("INSERT INTO Book_Note VALUES(81, 'First, but with four prequels...')")

    cursor.execute("CREATE TABLE Series_Book(Series_ID, Book_Id INT, Sequence_No INT)")
    cursor.execute("INSERT INTO Series_Book VALUES(1, 7, 4)")
    cursor.execute("INSERT INTO Series_Book VALUES( 1, 8, 3)")
    cursor.execute("INSERT INTO Series_Book VALUES( 1, 22, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 1, 25, 11)")
    cursor.execute("INSERT INTO Series_Book VALUES( 2, 14, 0)")
    cursor.execute("INSERT INTO Series_Book VALUES( 2, 15, 0)")
    cursor.execute("INSERT INTO Series_Book VALUES( 2, 25, 0)")
    cursor.execute("INSERT INTO Series_Book VALUES( 2, 181, 0)")
    cursor.execute("INSERT INTO Series_Book VALUES( 3, 18, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 3, 99, 2)")
    cursor.execute("INSERT INTO Series_Book VALUES( 3, 167, 3)")
    cursor.execute("INSERT INTO Series_Book VALUES( 3, 188, 4)")
    cursor.execute("INSERT INTO Series_Book VALUES( 4, 135, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 4, 21, 2)")
    cursor.execute("INSERT INTO Series_Book VALUES( 4, 86, 3)")
    cursor.execute("INSERT INTO Series_Book VALUES( 4, 137, 4)")
    cursor.execute("INSERT INTO Series_Book VALUES( 4, 192, 5)")
    cursor.execute("INSERT INTO Series_Book VALUES( 5, 28, 3)")
    cursor.execute("INSERT INTO Series_Book VALUES( 5, 29, 2)")
    cursor.execute("INSERT INTO Series_Book VALUES( 5, 30, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 6, 32, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 7, 76, 28)")
    cursor.execute("INSERT INTO Series_Book VALUES( 7, 127, 21)")
    cursor.execute("INSERT INTO Series_Book VALUES( 8, 47, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 8, 147, 12)")
    cursor.execute("INSERT INTO Series_Book VALUES( 9, 53, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 9, 54, 2)")
    cursor.execute("INSERT INTO Series_Book VALUES( 9, 55, 3)")
    cursor.execute("INSERT INTO Series_Book VALUES( 10, 59, 4)")
    cursor.execute("INSERT INTO Series_Book VALUES( 10, 60, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 10, 61, 2)")
    cursor.execute("INSERT INTO Series_Book VALUES( 10, 62, 3)")
    cursor.execute("INSERT INTO Series_Book VALUES( 11, 65, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 11, 66, 2)")
    cursor.execute("INSERT INTO Series_Book VALUES( 11, 67, 3)")
    cursor.execute("INSERT INTO Series_Book VALUES( 11, 68, 4)")
    cursor.execute("INSERT INTO Series_Book VALUES( 11, 69, 5)")
    cursor.execute("INSERT INTO Series_Book VALUES( 11, 70, 6)")
    cursor.execute("INSERT INTO Series_Book VALUES( 11, 71, 7)")
    cursor.execute("INSERT INTO Series_Book VALUES( 11, 72, 8)")
    cursor.execute("INSERT INTO Series_Book VALUES( 11, 73, 9)")
    cursor.execute("INSERT INTO Series_Book VALUES( 11, 74, 10)")
    cursor.execute("INSERT INTO Series_Book VALUES( 11, 75, 11)")
    cursor.execute("INSERT INTO Series_Book VALUES( 12, 71, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 12, 72, 2)")
    cursor.execute("INSERT INTO Series_Book VALUES( 12, 73, 3)")
    cursor.execute("INSERT INTO Series_Book VALUES( 12, 74, 4)")
    cursor.execute("INSERT INTO Series_Book VALUES( 12, 75, 5)")
    cursor.execute("INSERT INTO Series_Book VALUES( 13, 77, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 13, 78, 2)")
    cursor.execute("INSERT INTO Series_Book VALUES( 13, 79, 3)")
    cursor.execute("INSERT INTO Series_Book VALUES( 14, 81, 1')")
    cursor.execute("INSERT INTO Series_Book VALUES( 14, 82, 2)")
    cursor.execute("INSERT INTO Series_Book VALUES( 14, 83, 3)")
    cursor.execute("INSERT INTO Series_Book VALUES( 14, 84, 4)")
    cursor.execute("INSERT INTO Series_Book VALUES( 15, 87, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 15, 185, 2)")
    cursor.execute("INSERT INTO Series_Book VALUES( 16, 89, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 16, 90, 2)")
    cursor.execute("INSERT INTO Series_Book VALUES( 16, 91, 3)")
    cursor.execute("INSERT INTO Series_Book VALUES( 16, 92, 4)")
    cursor.execute("INSERT INTO Series_Book VALUES( 16, 93, 5)")
    cursor.execute("INSERT INTO Series_Book VALUES( 16, 94, 6)")
    cursor.execute("INSERT INTO Series_Book VALUES( 16, 95, 7)")
    cursor.execute("INSERT INTO Series_Book VALUES( 16, 96, 8)")
    cursor.execute("INSERT INTO Series_Book VALUES( 17, 97, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 17, 166, 2)")
    cursor.execute("INSERT INTO Series_Book VALUES( 18, 101, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 18, 102, 2)")
    cursor.execute("INSERT INTO Series_Book VALUES( 18, 103, 3)")
    cursor.execute("INSERT INTO Series_Book VALUES( 19, 108, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 19, 109, 2)")
    cursor.execute("INSERT INTO Series_Book VALUES( 19, 110, 3)")
    cursor.execute("INSERT INTO Series_Book VALUES( 19, 111, 4)")
    cursor.execute("INSERT INTO Series_Book VALUES( 19, 112, 5)")
    cursor.execute("INSERT INTO Series_Book VALUES( 20, 123, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 20, 124, 2)")
    cursor.execute("INSERT INTO Series_Book VALUES( 20, 125, 3)")
    cursor.execute("INSERT INTO Series_Book VALUES( 21, 126, 2)")
    cursor.execute("INSERT INTO Series_Book VALUES( 21, 130, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 22, 142, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 22, 186, 2)")
    cursor.execute("INSERT INTO Series_Book VALUES( 22, 189, 3)")
    cursor.execute("INSERT INTO Series_Book VALUES( 23, 145, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 24, 149, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 25, 154, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 25, 156, 2)")
    cursor.execute("INSERT INTO Series_Book VALUES( 25, 155, 5)")
    cursor.execute("INSERT INTO Series_Book VALUES( 26, 157, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 26, 158, 2)")
    cursor.execute("INSERT INTO Series_Book VALUES( 26, 159, 3)")
    cursor.execute("INSERT INTO Series_Book VALUES( 26, 160, 4)")
    cursor.execute("INSERT INTO Series_Book VALUES( 27, 168, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 28, 172, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 29, 173, 1)")
    cursor.execute("INSERT INTO Series_Book VALUES( 29, 174, 2)")
    cursor.execute("INSERT INTO Series_Book VALUES( 29, 175, 3)")
    cursor.execute("INSERT INTO Series_Book VALUES( 29, 176, 4)")

    cursor.execute("CREATE TABLE Series(Id TEXT, Title TEXT, Comment TEXT)")
    cursor.execute("INSERT INTO Series VALUES(1, 'Keller', 'Hit man who''s just an ordinary guy')")
    cursor.execute("INSERT INTO Series VALUES(2, 'Discworld', 'Turtles all the way down')")
    cursor.execute("INSERT INTO Series VALUES(3, 'Academy', '')")
    cursor.execute("INSERT INTO Series VALUES(4, 'Matthew Shardlake', 'Tudor Mysteries involving a lawyer close to the King')")
    cursor.execute("INSERT INTO Series VALUES(5, 'WWW Trilogy', 'Sentient internet')")
    cursor.execute("INSERT INTO Series VALUES(6, 'Psycho', 'The first is the classic, the rest look like cash-ins')")
    cursor.execute("INSERT INTO Series VALUES(7, 'Mammoth', 'Various genres in the series')")
    cursor.execute("INSERT INTO Series VALUES(8, 'Women of the Otherworld', 'Various heroines in the series, all fantasy types such as werewolves')")
    cursor.execute("INSERT INTO Series VALUES(9, 'Poseidon''s Children', 'Trilogy about the Akinyas')") 
    cursor.execute("INSERT INTO Series VALUES(10, 'The Shoal Sequence', 'Dakota Merrick gains FTL technology')")
    cursor.execute("INSERT INTO Series VALUES(11, 'The Lost Fleet', 'Black Jack Geary wins the war against the Syndics - first series, followed by Beyond the Frontier')")
    cursor.execute("INSERT INTO Series VALUES(12, 'Beyond the Frontier', 'Black Jack Geary rides again, exploring now - follows The Lost Fleet series')")
    cursor.execute("INSERT INTO Series VALUES(13, 'Orthogonal', 'Excellent trilogy set in a mathematically justified alternate universe')")
    cursor.execute("INSERT INTO Series VALUES(14, 'Ringworld', 'The Worlds series books are prequels to this')")
    cursor.execute("INSERT INTO Series VALUES(15, 'Luna', 'The moon is literally a cut-throat business world ruled by contract law')")
    cursor.execute("INSERT INTO Series VALUES(16, 'Chung Kuo', 'The Earth is now dominated by China, the population living in mega-cities')")
    cursor.execute("INSERT INTO Series VALUES(17, 'Matthew Scudder', 'Ex-policeman (a richochet killed a girl so he quit), recovering alcoholic, unlicenced private detective in NY')")
    cursor.execute("INSERT INTO Series VALUES(18, 'Imperial Radch', 'The dead are reanimated as extensions of a spaceship - essentially robots - but the ships themselves are conscious AIs')")
    cursor.execute("INSERT INTO Series VALUES(19, 'The Long Earth', 'Stepping out')")
    cursor.execute("INSERT INTO Series VALUES(20, 'Jean le Flambeur', 'The thief and solar system saviour')")
    cursor.execute("INSERT INTO Series VALUES(21, 'Alex Benedict', 'Antique dealer and investigator')")
    cursor.execute("INSERT INTO Series VALUES(22, 'Sherlock Holmes', 'The consulting detective')")
    cursor.execute("INSERT INTO Series VALUES(23, 'Elijah Bailey', 'The detective with a robot sidekick')")
    cursor.execute("INSERT INTO Series VALUES(24, 'The Expanse', 'Aliens seed Venus')")
    cursor.execute("INSERT INTO Series VALUES(25, 'Philip Marlowe', 'The P.I. par excellence')")
    cursor.execute("INSERT INTO Series VALUES(26, 'The Merchant Princes', 'A family that can step between parallel worlds uses this power to become princes of the less developed world')")
    cursor.execute("INSERT INTO Series VALUES(27, 'The Void Trilogy', 'The centre of the galaxy has an impenetrable void. Except someone seems to have penetrated it a dreamer discovers. Soon everyone wants to go there')")
    cursor.execute("INSERT INTO Series VALUES(28, 'Hunger Games', 'Tributes from vassal cities are pitted against each other in a modern arena')")
    cursor.execute("INSERT INTO Series VALUES(29, 'Earthsea', 'Following the adventures of Sparrowhawk, Archmage')")

    cursor.execute("CREATE TABLE Rating(Id TEXT, Rating TEXT, Description TEXT)")
    cursor.execute("INSERT INTO Rating VALUES('R', 'Reread', 'Reread this book')")
    cursor.execute("INSERT INTO Rating VALUES('A', 'All', 'Read all books by this author')")
    cursor.execute("INSERT INTO Rating VALUES('M', 'More', 'Read more books by this author')")
    cursor.execute("INSERT INTO Rating VALUES('T', 'Try again', 'Try another book by this author')")
    cursor.execute("INSERT INTO Rating VALUES('N', 'Never again', 'Avoid books by this author')")
    cursor.execute("INSERT INTO Rating VALUES('Y', 'Younger', 'Enjoyable if/when younger')")
    cursor.execute("INSERT INTO Rating VALUES('U', 'Unread', 'I have it but haven''t read it')")
    cursor.execute("INSERT INTO Rating VALUES('O', 'Order', 'Don''t have it but would like to read it')")
    
    db.commit()

def cleanUp():
    db.close()
    mainWindow.destroy()
    if helpWindow is not None:     # check helpWindow exists before trying to destroy it
        closeHelp()

def showHelp():
    global helpWindow                    # put it in globals so can be destroyed by other functions 
    if helpWindow is not None:
        closeHelp()
    helpWindow = Tk()
    title = Label(helpWindow, text="Help", font = "Verdana 10 bold", pady=10).pack()
    helpText = Text(helpWindow)
    helpText.pack()
    helpText.insert(END, "Put your guess in the box and click 'OK'")
    Button(helpWindow, text='Close', command=closeHelp).pack()

def closeHelp():
    global helpWindow
    helpWindow.destroy()
    helpWindow = None
    
def showAuthors():
    dataDisplayField.delete(1.0,END)
    cursor.execute("SELECT ID, Given_Name, Family_Name FROM Author ORDER BY Family_Name")
    data = cursor.fetchall()
    for row in data:
        dataDisplayField.insert(END,row)
        dataDisplayField.insert(END,"\n")
    selectButton.config(state=NORMAL, command=selectAuthor)   # enable author select

def showBooks():
    dataDisplayField.delete(1.0,END)
    cursor.execute("SELECT ID, Title, Rating FROM Book ORDER BY Title")
    data = cursor.fetchall()
    dataDisplayField.insert(END, "ID\tTitle\tRating\n")
    dataDisplayField.insert(END, "------------------------------------\n")
    for row in data:
        dataDisplayField.insert(END,row[0])
        dataDisplayField.insert(END,"\t")
        dataDisplayField.insert(END,row[1])
        dataDisplayField.insert(END,"\t")
        dataDisplayField.insert(END,row[2])
        dataDisplayField.insert(END,"\n")
#    selectButton.config(state=NORMAL, command=selectBook)   # enable book select


def showByChanged(*args):
    newChoice = showByChoice.get()
    if newChoice == "Show by author":
        showAuthors()
    else:
        showBooks()
        

def selectBookByID():
    bookIDselected = IDselect.get()
    cursor.execute("SELECT Title, Comment, Rating FROM Book WHERE ID=" + bookIDselected)
    title = cursor.fetchone()
    selectDisplay1.delete(0,END)        # clear the field
    selectDisplay1.insert(END,title[0])
    selectDisplay2.delete(0,END)        # clear the field
    selectDisplay2.insert(END,title[1])
    selectDisplay3.delete(0,END)        # clear the field
    selectDisplay3.insert(END,title[2])

    
def selectAuthor():
    authorIDselected = IDselect.get()
    cursor.execute("SELECT * FROM Author WHERE Family_Name LIKE '" + toMatch + "%' ORDER BY Family_Name")
    data = cursor.fetchall()




authorNames = None
authorIDs = None

def matchAuthors(*args):
    global authorNames, authorIDs
    toMatch = authorValue.get()
    cursor.execute("SELECT * FROM Author WHERE Family_Name LIKE '" + toMatch + "%' ORDER BY Family_Name")
    data = cursor.fetchall()
    authorNames = []
    authorIDs = []
    for row in data:
        author = row[2] + ", " + row[1]
        authorNames.append(author)
        authorIDs.append(row[0])
    authorSearchEntry.configure(values = authorNames)

def showOuevre(*args):
    dataDisplayField.config(tabs="1c, 4c")      # sets tabs at 1cm and 4cm
    ####
    # Next line is a kludge
    cursor.execute("SELECT * FROM Author WHERE Family_Name LIKE '" + authorNames[0][0:3] + "%' ORDER BY Family_Name")
    data = cursor.fetchall()
    dataDisplayField.delete(1.0,END)            # clear it
    for row in data:
        dataDisplayField.insert(END,row[0])
        dataDisplayField.insert(END,": ")
        dataDisplayField.insert(END,row[1])
        dataDisplayField.insert(END," ")
        dataDisplayField.insert(END,row[2])
        dataDisplayField.insert(END,"\n")
        cursor.execute("SELECT * FROM Author_Book WHERE Author=" + str(row[0]))
        booksData = cursor.fetchall()
        for row in booksData:
            cursor.execute("SELECT * FROM Book WHERE Id=" + str(row[0]))
            bookData = cursor.fetchone()
            dataDisplayField.insert(END,bookData[0])
            dataDisplayField.insert(END," (")
            dataDisplayField.insert(END,bookData[3])
            dataDisplayField.insert(END,"): '")
            dataDisplayField.insert(END,bookData[1])
            dataDisplayField.insert(END,"' - ")
            dataDisplayField.insert(END,bookData[2])
            dataDisplayField.insert(END,"\n")
        dataDisplayField.insert(END,"\n")


    
# Set up the main window
mainWindow = Tk()
mainWindow.title("Book store")
title = Label(mainWindow, text="Book list", font = "Verdana 10 bold", pady=10)
title.grid(row=0, column=0, columnspan=3)

# button to re-setup the d/b
resetButton = Button(mainWindow, text='Reset DB', command=setupDB)
resetButton.grid(row=3, column=2)

# Set up the book search area
bookFrame = Frame(mainWindow)
bookFrame.grid(row=1, column=0, columnspan=3, sticky=W)
Label(bookFrame, text="Search by book").pack(side=LEFT, padx=(5,0))
bookSearchEntry = Entry(bookFrame)
bookSearchEntry.pack(padx=10, side=LEFT)
bookSearchOK = Button(bookFrame, text='OK', command=None).pack(side=LEFT)

# Set up the author search area
Label(bookFrame, text="Author").pack(side=LEFT, padx=(15,0))
authorValue = StringVar()
authorValue.trace_variable("w", matchAuthors)   # called when value changed
authorSearchEntry = ttk.Combobox(bookFrame, textvariable = authorValue)
authorSearchEntry.pack(padx=10, side=LEFT)
authorSearchOK = Button(bookFrame, text = 'OK', command = showOuevre).pack(side=LEFT)



# Set up the data display area
# First the 'show by' button/menu
showByChoice = StringVar(mainWindow)
showByChoice.set("Show by ...")
showByChoice.trace_variable("w", showByChanged)   # showByChanged() called when value changed
showByDropdown = OptionMenu(mainWindow, showByChoice, "Show by author", "Show by title")
showByDropdown.grid(row=3, column=0, sticky=N)
# then the text display field
dataDisplayField = Text(mainWindow, height=10, width=40)
dataDisplayField.grid(row=3, column=1, pady=5)
dataDisplayField.config(tabs="1c, 7c")      # sets tabs at 1cm and 6cm

# Set up the selection area
Label(mainWindow, text="Select").grid(row=4, column=0)
# IDselect allows the user to type in an ID to select a record
IDselect = Entry(mainWindow)
IDselect.grid(row=4, column=1, padx=10)
# To select the record the user clicks the selectButton
selectButton = Button(mainWindow, disabledforeground="grey", text='OK')
selectButton.config(state=DISABLED) # disable the button until records shown
selectButton.grid(row=4, column=2)
# selectDisplay fields show the different fields of the selected record
selectDisplay1 = Entry(mainWindow)
selectDisplay1.grid(row=5, column=0)
selectDisplay2 = Entry(mainWindow)
selectDisplay2.grid(row=5, column=1)
selectDisplay3 = Entry(mainWindow)
selectDisplay3.grid(row=5, column=2)
# Click deleteButton to delete the selected record
deleteButton = Button(mainWindow, text='Delete')
deleteButton.grid(row=6, column=2)
# Click saveEditButton to save your changes to the selected record
saveEditButton = Button(mainWindow, text='Save')
saveEditButton.grid(row=6, column=1)


# Set up help/quit buttons
Button(mainWindow, text='Help', command=showHelp).grid(row=7, column=1, pady=10)
Button(mainWindow, text='Quit', command=cleanUp).grid(row=7, column=2, pady=10, padx=10)

# Connect to the database
db = sqlite3.connect("books.db")
cursor = db.cursor()


# Off we go
mainWindow.mainloop()

